// Auto-generated. Do not edit!

// (in-package cares_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let CutPoint = require('./CutPoint.js');

//-----------------------------------------------------------

class CutGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.command = null;
      this.cutting_frame = null;
      this.planning_frame = null;
      this.cut_points = null;
    }
    else {
      if (initObj.hasOwnProperty('command')) {
        this.command = initObj.command
      }
      else {
        this.command = 0;
      }
      if (initObj.hasOwnProperty('cutting_frame')) {
        this.cutting_frame = initObj.cutting_frame
      }
      else {
        this.cutting_frame = '';
      }
      if (initObj.hasOwnProperty('planning_frame')) {
        this.planning_frame = initObj.planning_frame
      }
      else {
        this.planning_frame = '';
      }
      if (initObj.hasOwnProperty('cut_points')) {
        this.cut_points = initObj.cut_points
      }
      else {
        this.cut_points = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CutGoal
    // Serialize message field [command]
    bufferOffset = _serializer.uint8(obj.command, buffer, bufferOffset);
    // Serialize message field [cutting_frame]
    bufferOffset = _serializer.string(obj.cutting_frame, buffer, bufferOffset);
    // Serialize message field [planning_frame]
    bufferOffset = _serializer.string(obj.planning_frame, buffer, bufferOffset);
    // Serialize message field [cut_points]
    // Serialize the length for message field [cut_points]
    bufferOffset = _serializer.uint32(obj.cut_points.length, buffer, bufferOffset);
    obj.cut_points.forEach((val) => {
      bufferOffset = CutPoint.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CutGoal
    let len;
    let data = new CutGoal(null);
    // Deserialize message field [command]
    data.command = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [cutting_frame]
    data.cutting_frame = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [planning_frame]
    data.planning_frame = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [cut_points]
    // Deserialize array length for message field [cut_points]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.cut_points = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.cut_points[i] = CutPoint.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.cutting_frame);
    length += _getByteLength(object.planning_frame);
    length += 48 * object.cut_points.length;
    return length + 13;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cares_msgs/CutGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f760b5a102c579d359a8e31180574d7a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint8 CUT = 0
    uint8 STOP = 1
    uint8 command
    
    string cutting_frame
    string planning_frame
    cares_msgs/CutPoint[] cut_points
    
    ================================================================================
    MSG: cares_msgs/CutPoint
    geometry_msgs/Point cut_point_a
    geometry_msgs/Point cut_point_b
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CutGoal(null);
    if (msg.command !== undefined) {
      resolved.command = msg.command;
    }
    else {
      resolved.command = 0
    }

    if (msg.cutting_frame !== undefined) {
      resolved.cutting_frame = msg.cutting_frame;
    }
    else {
      resolved.cutting_frame = ''
    }

    if (msg.planning_frame !== undefined) {
      resolved.planning_frame = msg.planning_frame;
    }
    else {
      resolved.planning_frame = ''
    }

    if (msg.cut_points !== undefined) {
      resolved.cut_points = new Array(msg.cut_points.length);
      for (let i = 0; i < resolved.cut_points.length; ++i) {
        resolved.cut_points[i] = CutPoint.Resolve(msg.cut_points[i]);
      }
    }
    else {
      resolved.cut_points = []
    }

    return resolved;
    }
};

// Constants for message
CutGoal.Constants = {
  CUT: 0,
  STOP: 1,
}

module.exports = CutGoal;
