// Auto-generated. Do not edit!

// (in-package cares_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Vine = require('./Vine.js');
let Fruitlets = require('./Fruitlets.js');
let sensor_msgs = _finder('sensor_msgs');

//-----------------------------------------------------------

class MetricExtractionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result = null;
      this.vine = null;
      this.fruitlets = null;
      this.point_cloud = null;
    }
    else {
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = 0;
      }
      if (initObj.hasOwnProperty('vine')) {
        this.vine = initObj.vine
      }
      else {
        this.vine = new Vine();
      }
      if (initObj.hasOwnProperty('fruitlets')) {
        this.fruitlets = initObj.fruitlets
      }
      else {
        this.fruitlets = new Fruitlets();
      }
      if (initObj.hasOwnProperty('point_cloud')) {
        this.point_cloud = initObj.point_cloud
      }
      else {
        this.point_cloud = new sensor_msgs.msg.PointCloud2();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MetricExtractionResult
    // Serialize message field [result]
    bufferOffset = _serializer.uint8(obj.result, buffer, bufferOffset);
    // Serialize message field [vine]
    bufferOffset = Vine.serialize(obj.vine, buffer, bufferOffset);
    // Serialize message field [fruitlets]
    bufferOffset = Fruitlets.serialize(obj.fruitlets, buffer, bufferOffset);
    // Serialize message field [point_cloud]
    bufferOffset = sensor_msgs.msg.PointCloud2.serialize(obj.point_cloud, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MetricExtractionResult
    let len;
    let data = new MetricExtractionResult(null);
    // Deserialize message field [result]
    data.result = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [vine]
    data.vine = Vine.deserialize(buffer, bufferOffset);
    // Deserialize message field [fruitlets]
    data.fruitlets = Fruitlets.deserialize(buffer, bufferOffset);
    // Deserialize message field [point_cloud]
    data.point_cloud = sensor_msgs.msg.PointCloud2.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += Vine.getMessageSize(object.vine);
    length += Fruitlets.getMessageSize(object.fruitlets);
    length += sensor_msgs.msg.PointCloud2.getMessageSize(object.point_cloud);
    return length + 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cares_msgs/MetricExtractionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c2a9ce6ac04d25549c31e0c74e3f8c2d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    uint8 result
    cares_msgs/Vine vine
    cares_msgs/Fruitlets fruitlets
    sensor_msgs/PointCloud2 point_cloud
    
    ================================================================================
    MSG: cares_msgs/Vine
    cares_msgs/Cane[] cane_list
    ================================================================================
    MSG: cares_msgs/Cane
    uint8 cane_id
    uint8 cane_type
    
    float64 internode_length
    float64 internode_width
    uint8 node_count
    
    cares_msgs/Node[] node_list
    cares_msgs/Node origin_node
    
    ================================================================================
    MSG: cares_msgs/Node
    uint32 node_id
    
    #Node Type
    uint8  PRIMARY_ORIGIN_NODE = 0
    uint8  REGULAR_NODE = 1
    uint8  MULTI_NODE = 2
    uint8  UNLINKED_NODE = 3
    uint8  node_type
    
    geometry_msgs/Point position
    
    uint32 sequencial_neighbour_id
    cares_msgs/NodeNeighbourInfo[] neighbours
    
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: cares_msgs/NodeNeighbourInfo
    uint32 neighbour_id
    float64 internode_length
    float64 internode_width
    ================================================================================
    MSG: cares_msgs/Fruitlets
    cares_msgs/Fruitlet[] fruitlets 
    
    ================================================================================
    MSG: cares_msgs/Fruitlet
    uint8 ID
    geometry_msgs/Point centroid
    geometry_msgs/Point calyx 
    float32 radius
    bool chosen_one
    
    ================================================================================
    MSG: sensor_msgs/PointCloud2
    # This message holds a collection of N-dimensional points, which may
    # contain additional information such as normals, intensity, etc. The
    # point data is stored as a binary blob, its layout described by the
    # contents of the "fields" array.
    
    # The point cloud data may be organized 2d (image-like) or 1d
    # (unordered). Point clouds organized as 2d images may be produced by
    # camera depth sensors such as stereo or time-of-flight.
    
    # Time of sensor data acquisition, and the coordinate frame ID (for 3d
    # points).
    Header header
    
    # 2D structure of the point cloud. If the cloud is unordered, height is
    # 1 and width is the length of the point cloud.
    uint32 height
    uint32 width
    
    # Describes the channels and their layout in the binary data blob.
    PointField[] fields
    
    bool    is_bigendian # Is this data bigendian?
    uint32  point_step   # Length of a point in bytes
    uint32  row_step     # Length of a row in bytes
    uint8[] data         # Actual point data, size is (row_step*height)
    
    bool is_dense        # True if there are no invalid points
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: sensor_msgs/PointField
    # This message holds the description of one point entry in the
    # PointCloud2 message format.
    uint8 INT8    = 1
    uint8 UINT8   = 2
    uint8 INT16   = 3
    uint8 UINT16  = 4
    uint8 INT32   = 5
    uint8 UINT32  = 6
    uint8 FLOAT32 = 7
    uint8 FLOAT64 = 8
    
    string name      # Name of field
    uint32 offset    # Offset from start of point struct
    uint8  datatype  # Datatype enumeration, see above
    uint32 count     # How many elements in the field
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MetricExtractionResult(null);
    if (msg.result !== undefined) {
      resolved.result = msg.result;
    }
    else {
      resolved.result = 0
    }

    if (msg.vine !== undefined) {
      resolved.vine = Vine.Resolve(msg.vine)
    }
    else {
      resolved.vine = new Vine()
    }

    if (msg.fruitlets !== undefined) {
      resolved.fruitlets = Fruitlets.Resolve(msg.fruitlets)
    }
    else {
      resolved.fruitlets = new Fruitlets()
    }

    if (msg.point_cloud !== undefined) {
      resolved.point_cloud = sensor_msgs.msg.PointCloud2.Resolve(msg.point_cloud)
    }
    else {
      resolved.point_cloud = new sensor_msgs.msg.PointCloud2()
    }

    return resolved;
    }
};

module.exports = MetricExtractionResult;
