obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.5, 0.4], [0.5, -0.4], [-0.5, -0.4], [-0.5, 0.4]]
#robot_radius: 0.5
inflation_radius: 0.2

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

#layer definitions
# static:
#     map_topic: map
#     subscribe_to_updates: true

# obstacles_laser:
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan_filtered, inf_is_valid: true}

# inflation:
#     inflation_radius: 1.0