global_costmap:
  global_frame: map
  #map_type: costmap
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false
  width: 20.0
  height: 20.0
  resolution: 0.05
  origin_x: -10.0 
  origin_y: -10.0

