; Auto-generated. Do not edit!


(cl:in-package cares_msgs-msg)


;//! \htmlinclude CutFeedback.msg.html

(cl:defclass <CutFeedback> (roslisp-msg-protocol:ros-message)
  ((count
    :reader count
    :initarg :count
    :type cl:fixnum
    :initform 0)
   (total
    :reader total
    :initarg :total
    :type cl:fixnum
    :initform 0)
   (status
    :reader status
    :initarg :status
    :type cl:fixnum
    :initform 0)
   (actuation_feedback
    :reader actuation_feedback
    :initarg :actuation_feedback
    :type cares_msgs-msg:ActuationFeedback
    :initform (cl:make-instance 'cares_msgs-msg:ActuationFeedback)))
)

(cl:defclass CutFeedback (<CutFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CutFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CutFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cares_msgs-msg:<CutFeedback> is deprecated: use cares_msgs-msg:CutFeedback instead.")))

(cl:ensure-generic-function 'count-val :lambda-list '(m))
(cl:defmethod count-val ((m <CutFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:count-val is deprecated.  Use cares_msgs-msg:count instead.")
  (count m))

(cl:ensure-generic-function 'total-val :lambda-list '(m))
(cl:defmethod total-val ((m <CutFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:total-val is deprecated.  Use cares_msgs-msg:total instead.")
  (total m))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <CutFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:status-val is deprecated.  Use cares_msgs-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'actuation_feedback-val :lambda-list '(m))
(cl:defmethod actuation_feedback-val ((m <CutFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:actuation_feedback-val is deprecated.  Use cares_msgs-msg:actuation_feedback instead.")
  (actuation_feedback m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<CutFeedback>)))
    "Constants for message type '<CutFeedback>"
  '((:INIT . 0)
    (:PROCESSING_CUT_POINTS . 1)
    (:MAKING_CUT . 2)
    (:STOPPING . 3)
    (:TRANSITIONING . 4))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'CutFeedback)))
    "Constants for message type 'CutFeedback"
  '((:INIT . 0)
    (:PROCESSING_CUT_POINTS . 1)
    (:MAKING_CUT . 2)
    (:STOPPING . 3)
    (:TRANSITIONING . 4))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CutFeedback>) ostream)
  "Serializes a message object of type '<CutFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'status)) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'actuation_feedback) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CutFeedback>) istream)
  "Deserializes a message object of type '<CutFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'status)) (cl:read-byte istream))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'actuation_feedback) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CutFeedback>)))
  "Returns string type for a message object of type '<CutFeedback>"
  "cares_msgs/CutFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CutFeedback)))
  "Returns string type for a message object of type 'CutFeedback"
  "cares_msgs/CutFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CutFeedback>)))
  "Returns md5sum for a message object of type '<CutFeedback>"
  "135f6e5cf0a3fa4efd93ea37e026037d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CutFeedback)))
  "Returns md5sum for a message object of type 'CutFeedback"
  "135f6e5cf0a3fa4efd93ea37e026037d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CutFeedback>)))
  "Returns full string definition for message of type '<CutFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 count~%uint8 total~%~%uint8 INIT = 0~%uint8 PROCESSING_CUT_POINTS = 1~%uint8 MAKING_CUT = 2~%uint8 STOPPING = 3~%uint8 TRANSITIONING = 4~%~%uint8 status~%~%cares_msgs/ActuationFeedback actuation_feedback~%~%~%================================================================================~%MSG: cares_msgs/ActuationFeedback~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 INIT       = 0~%uint8 MOVING_TO_APPROACH = 1~%uint8 MOVING_TO_TARGET   = 3~%uint8 MOVING_BACK_TO_APPROACH   = 4~%uint8 ACTUATING          = 5~%uint8 STOPPING           = 6~%~%uint8 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CutFeedback)))
  "Returns full string definition for message of type 'CutFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 count~%uint8 total~%~%uint8 INIT = 0~%uint8 PROCESSING_CUT_POINTS = 1~%uint8 MAKING_CUT = 2~%uint8 STOPPING = 3~%uint8 TRANSITIONING = 4~%~%uint8 status~%~%cares_msgs/ActuationFeedback actuation_feedback~%~%~%================================================================================~%MSG: cares_msgs/ActuationFeedback~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 INIT       = 0~%uint8 MOVING_TO_APPROACH = 1~%uint8 MOVING_TO_TARGET   = 3~%uint8 MOVING_BACK_TO_APPROACH   = 4~%uint8 ACTUATING          = 5~%uint8 STOPPING           = 6~%~%uint8 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CutFeedback>))
  (cl:+ 0
     1
     1
     1
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'actuation_feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CutFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CutFeedback
    (cl:cons ':count (count msg))
    (cl:cons ':total (total msg))
    (cl:cons ':status (status msg))
    (cl:cons ':actuation_feedback (actuation_feedback msg))
))
