; Auto-generated. Do not edit!


(cl:in-package cares_msgs-msg)


;//! \htmlinclude ScanningFeedback.msg.html

(cl:defclass <ScanningFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:fixnum
    :initform 0)
   (arm_status
    :reader arm_status
    :initarg :arm_status
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ScanningFeedback (<ScanningFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ScanningFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ScanningFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cares_msgs-msg:<ScanningFeedback> is deprecated: use cares_msgs-msg:ScanningFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <ScanningFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:status-val is deprecated.  Use cares_msgs-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'arm_status-val :lambda-list '(m))
(cl:defmethod arm_status-val ((m <ScanningFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:arm_status-val is deprecated.  Use cares_msgs-msg:arm_status instead.")
  (arm_status m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<ScanningFeedback>)))
    "Constants for message type '<ScanningFeedback>"
  '((:INIT . 0)
    (:MARKER . 1)
    (:CAPTURING . 2)
    (:ERROR . 3)
    (:MOVING . 4)
    (:IDLE . 5))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'ScanningFeedback)))
    "Constants for message type 'ScanningFeedback"
  '((:INIT . 0)
    (:MARKER . 1)
    (:CAPTURING . 2)
    (:ERROR . 3)
    (:MOVING . 4)
    (:IDLE . 5))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ScanningFeedback>) ostream)
  "Serializes a message object of type '<ScanningFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'status)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'arm_status)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ScanningFeedback>) istream)
  "Deserializes a message object of type '<ScanningFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'status)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'arm_status)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ScanningFeedback>)))
  "Returns string type for a message object of type '<ScanningFeedback>"
  "cares_msgs/ScanningFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ScanningFeedback)))
  "Returns string type for a message object of type 'ScanningFeedback"
  "cares_msgs/ScanningFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ScanningFeedback>)))
  "Returns md5sum for a message object of type '<ScanningFeedback>"
  "a831927301716bc558cf8f21c5d38a0a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ScanningFeedback)))
  "Returns md5sum for a message object of type 'ScanningFeedback"
  "a831927301716bc558cf8f21c5d38a0a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ScanningFeedback>)))
  "Returns full string definition for message of type '<ScanningFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%#Enumeration~%uint8 INIT       = 0~%uint8 MARKER     = 1~%uint8 CAPTURING  = 2~%uint8 ERROR      = 3~%#Task status~%uint8 status~%~%#Enumeration~%uint8 MOVING  = 4~%uint8 IDLE    = 5~%uint8 arm_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ScanningFeedback)))
  "Returns full string definition for message of type 'ScanningFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%#Enumeration~%uint8 INIT       = 0~%uint8 MARKER     = 1~%uint8 CAPTURING  = 2~%uint8 ERROR      = 3~%#Task status~%uint8 status~%~%#Enumeration~%uint8 MOVING  = 4~%uint8 IDLE    = 5~%uint8 arm_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ScanningFeedback>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ScanningFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ScanningFeedback
    (cl:cons ':status (status msg))
    (cl:cons ':arm_status (arm_status msg))
))
