# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cares_msgs/Metrics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Metrics(genpy.Message):
  _md5sum = "50ad2f167aef563f731444e44444c393"
  _type = "cares_msgs/Metrics"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 ID
geometry_msgs/Point centroid
geometry_msgs/Point calyx 
float32 Radius
bool chosen_one

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['ID','centroid','calyx','Radius','chosen_one']
  _slot_types = ['uint8','geometry_msgs/Point','geometry_msgs/Point','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,centroid,calyx,Radius,chosen_one

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Metrics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.calyx is None:
        self.calyx = geometry_msgs.msg.Point()
      if self.Radius is None:
        self.Radius = 0.
      if self.chosen_one is None:
        self.chosen_one = False
    else:
      self.ID = 0
      self.centroid = geometry_msgs.msg.Point()
      self.calyx = geometry_msgs.msg.Point()
      self.Radius = 0.
      self.chosen_one = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B6dfB().pack(_x.ID, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.calyx.x, _x.calyx.y, _x.calyx.z, _x.Radius, _x.chosen_one))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.calyx is None:
        self.calyx = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 54
      (_x.ID, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.calyx.x, _x.calyx.y, _x.calyx.z, _x.Radius, _x.chosen_one,) = _get_struct_B6dfB().unpack(str[start:end])
      self.chosen_one = bool(self.chosen_one)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B6dfB().pack(_x.ID, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.calyx.x, _x.calyx.y, _x.calyx.z, _x.Radius, _x.chosen_one))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.calyx is None:
        self.calyx = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 54
      (_x.ID, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.calyx.x, _x.calyx.y, _x.calyx.z, _x.Radius, _x.chosen_one,) = _get_struct_B6dfB().unpack(str[start:end])
      self.chosen_one = bool(self.chosen_one)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B6dfB = None
def _get_struct_B6dfB():
    global _struct_B6dfB
    if _struct_B6dfB is None:
        _struct_B6dfB = struct.Struct("<B6dfB")
    return _struct_B6dfB
