# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cares_msgs/ThinResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cares_msgs.msg
import geometry_msgs.msg

class ThinResult(genpy.Message):
  _md5sum = "8c9c3d8639eec8f454cb407630537d31"
  _type = "cares_msgs/ThinResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
uint8 result
cares_msgs/Fruitlet[] succeeded
cares_msgs/Fruitlet[] failed

================================================================================
MSG: cares_msgs/Fruitlet
uint8 ID
geometry_msgs/Point centroid
geometry_msgs/Point calyx 
float32 radius
bool chosen_one

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['result','succeeded','failed']
  _slot_types = ['uint8','cares_msgs/Fruitlet[]','cares_msgs/Fruitlet[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result,succeeded,failed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ThinResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = 0
      if self.succeeded is None:
        self.succeeded = []
      if self.failed is None:
        self.failed = []
    else:
      self.result = 0
      self.succeeded = []
      self.failed = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.result
      buff.write(_get_struct_B().pack(_x))
      length = len(self.succeeded)
      buff.write(_struct_I.pack(length))
      for val1 in self.succeeded:
        _x = val1.ID
        buff.write(_get_struct_B().pack(_x))
        _v1 = val1.centroid
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.calyx
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_fB().pack(_x.radius, _x.chosen_one))
      length = len(self.failed)
      buff.write(_struct_I.pack(length))
      for val1 in self.failed:
        _x = val1.ID
        buff.write(_get_struct_B().pack(_x))
        _v3 = val1.centroid
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v4 = val1.calyx
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_fB().pack(_x.radius, _x.chosen_one))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.succeeded is None:
        self.succeeded = None
      if self.failed is None:
        self.failed = None
      end = 0
      start = end
      end += 1
      (self.result,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.succeeded = []
      for i in range(0, length):
        val1 = cares_msgs.msg.Fruitlet()
        start = end
        end += 1
        (val1.ID,) = _get_struct_B().unpack(str[start:end])
        _v5 = val1.centroid
        _x = _v5
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v6 = val1.calyx
        _x = _v6
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 5
        (_x.radius, _x.chosen_one,) = _get_struct_fB().unpack(str[start:end])
        val1.chosen_one = bool(val1.chosen_one)
        self.succeeded.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.failed = []
      for i in range(0, length):
        val1 = cares_msgs.msg.Fruitlet()
        start = end
        end += 1
        (val1.ID,) = _get_struct_B().unpack(str[start:end])
        _v7 = val1.centroid
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.calyx
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 5
        (_x.radius, _x.chosen_one,) = _get_struct_fB().unpack(str[start:end])
        val1.chosen_one = bool(val1.chosen_one)
        self.failed.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.result
      buff.write(_get_struct_B().pack(_x))
      length = len(self.succeeded)
      buff.write(_struct_I.pack(length))
      for val1 in self.succeeded:
        _x = val1.ID
        buff.write(_get_struct_B().pack(_x))
        _v9 = val1.centroid
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v10 = val1.calyx
        _x = _v10
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_fB().pack(_x.radius, _x.chosen_one))
      length = len(self.failed)
      buff.write(_struct_I.pack(length))
      for val1 in self.failed:
        _x = val1.ID
        buff.write(_get_struct_B().pack(_x))
        _v11 = val1.centroid
        _x = _v11
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v12 = val1.calyx
        _x = _v12
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_fB().pack(_x.radius, _x.chosen_one))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.succeeded is None:
        self.succeeded = None
      if self.failed is None:
        self.failed = None
      end = 0
      start = end
      end += 1
      (self.result,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.succeeded = []
      for i in range(0, length):
        val1 = cares_msgs.msg.Fruitlet()
        start = end
        end += 1
        (val1.ID,) = _get_struct_B().unpack(str[start:end])
        _v13 = val1.centroid
        _x = _v13
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v14 = val1.calyx
        _x = _v14
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 5
        (_x.radius, _x.chosen_one,) = _get_struct_fB().unpack(str[start:end])
        val1.chosen_one = bool(val1.chosen_one)
        self.succeeded.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.failed = []
      for i in range(0, length):
        val1 = cares_msgs.msg.Fruitlet()
        start = end
        end += 1
        (val1.ID,) = _get_struct_B().unpack(str[start:end])
        _v15 = val1.centroid
        _x = _v15
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v16 = val1.calyx
        _x = _v16
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 5
        (_x.radius, _x.chosen_one,) = _get_struct_fB().unpack(str[start:end])
        val1.chosen_one = bool(val1.chosen_one)
        self.failed.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_fB = None
def _get_struct_fB():
    global _struct_fB
    if _struct_fB is None:
        _struct_fB = struct.Struct("<fB")
    return _struct_fB
