// Generated by gencpp from file cares_msgs/ActuationFeedback.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_ACTUATIONFEEDBACK_H
#define CARES_MSGS_MESSAGE_ACTUATIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cares_msgs
{
template <class ContainerAllocator>
struct ActuationFeedback_
{
  typedef ActuationFeedback_<ContainerAllocator> Type;

  ActuationFeedback_()
    : feedback(0)  {
    }
  ActuationFeedback_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef uint8_t _feedback_type;
  _feedback_type feedback;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INIT)
  #undef INIT
#endif
#if defined(_WIN32) && defined(MOVING_TO_APPROACH)
  #undef MOVING_TO_APPROACH
#endif
#if defined(_WIN32) && defined(MOVING_TO_TARGET)
  #undef MOVING_TO_TARGET
#endif
#if defined(_WIN32) && defined(MOVING_BACK_TO_APPROACH)
  #undef MOVING_BACK_TO_APPROACH
#endif
#if defined(_WIN32) && defined(ACTUATING)
  #undef ACTUATING
#endif
#if defined(_WIN32) && defined(STOPPING)
  #undef STOPPING
#endif

  enum {
    INIT = 0u,
    MOVING_TO_APPROACH = 1u,
    MOVING_TO_TARGET = 3u,
    MOVING_BACK_TO_APPROACH = 4u,
    ACTUATING = 5u,
    STOPPING = 6u,
  };


  typedef boost::shared_ptr< ::cares_msgs::ActuationFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::ActuationFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ActuationFeedback_

typedef ::cares_msgs::ActuationFeedback_<std::allocator<void> > ActuationFeedback;

typedef boost::shared_ptr< ::cares_msgs::ActuationFeedback > ActuationFeedbackPtr;
typedef boost::shared_ptr< ::cares_msgs::ActuationFeedback const> ActuationFeedbackConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::ActuationFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::ActuationFeedback_<ContainerAllocator1> & lhs, const ::cares_msgs::ActuationFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::ActuationFeedback_<ContainerAllocator1> & lhs, const ::cares_msgs::ActuationFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ActuationFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ActuationFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ActuationFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "285900cd61eb7f7690e543227e429ad8";
  }

  static const char* value(const ::cares_msgs::ActuationFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x285900cd61eb7f76ULL;
  static const uint64_t static_value2 = 0x90e543227e429ad8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/ActuationFeedback";
  }

  static const char* value(const ::cares_msgs::ActuationFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 INIT       = 0\n"
"uint8 MOVING_TO_APPROACH = 1\n"
"uint8 MOVING_TO_TARGET   = 3\n"
"uint8 MOVING_BACK_TO_APPROACH   = 4\n"
"uint8 ACTUATING          = 5\n"
"uint8 STOPPING           = 6\n"
"\n"
"uint8 feedback\n"
"\n"
;
  }

  static const char* value(const ::cares_msgs::ActuationFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuationFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::ActuationFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::ActuationFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_ACTUATIONFEEDBACK_H
