// Generated by gencpp from file cares_msgs/ArchieRailCmdAction.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_ARCHIERAILCMDACTION_H
#define CARES_MSGS_MESSAGE_ARCHIERAILCMDACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cares_msgs/ArchieRailCmdActionGoal.h>
#include <cares_msgs/ArchieRailCmdActionResult.h>
#include <cares_msgs/ArchieRailCmdActionFeedback.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct ArchieRailCmdAction_
{
  typedef ArchieRailCmdAction_<ContainerAllocator> Type;

  ArchieRailCmdAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ArchieRailCmdAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::cares_msgs::ArchieRailCmdActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::cares_msgs::ArchieRailCmdActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::cares_msgs::ArchieRailCmdActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> const> ConstPtr;

}; // struct ArchieRailCmdAction_

typedef ::cares_msgs::ArchieRailCmdAction_<std::allocator<void> > ArchieRailCmdAction;

typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdAction > ArchieRailCmdActionPtr;
typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdAction const> ArchieRailCmdActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator1> & lhs, const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator1> & lhs, const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de568f6522297b6e38a9bce2802ca3de";
  }

  static const char* value(const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde568f6522297b6eULL;
  static const uint64_t static_value2 = 0x38a9bce2802ca3deULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/ArchieRailCmdAction";
  }

  static const char* value(const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"ArchieRailCmdActionGoal action_goal\n"
"ArchieRailCmdActionResult action_result\n"
"ArchieRailCmdActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ArchieRailCmdActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ArchieRailCmdGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ArchieRailCmdGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"std_msgs/Header header\n"
"\n"
"geometry_msgs/PoseStamped target_pose\n"
"\n"
"uint8 MOVE  = 0\n"
"uint8 STOP  = 1\n"
"uint8 RESET = 2\n"
"uint8 START = 3\n"
"uint8 HOME  = 4\n"
"\n"
"# 5-255 reserved for future use\n"
"uint8 command\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ArchieRailCmdActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ArchieRailCmdResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ArchieRailCmdResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ArchieRailCmdActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ArchieRailCmdFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ArchieRailCmdFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"uint8 INIT      = 0\n"
"uint8 MOVING    = 1\n"
"uint8 STOPPING  = 2\n"
"uint8 RESETTING = 3\n"
"uint8 STARTING  = 4\n"
"uint8 HOMING    = 5\n"
"\n"
"# 5-255 reserved for future use\n"
"uint8 status\n"
"\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
;
  }

  static const char* value(const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArchieRailCmdAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::ArchieRailCmdAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::cares_msgs::ArchieRailCmdActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::cares_msgs::ArchieRailCmdActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::cares_msgs::ArchieRailCmdActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_ARCHIERAILCMDACTION_H
