// Generated by gencpp from file cares_msgs/ArchieRailCmdGoal.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_ARCHIERAILCMDGOAL_H
#define CARES_MSGS_MESSAGE_ARCHIERAILCMDGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct ArchieRailCmdGoal_
{
  typedef ArchieRailCmdGoal_<ContainerAllocator> Type;

  ArchieRailCmdGoal_()
    : header()
    , target_pose()
    , command(0)  {
    }
  ArchieRailCmdGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , target_pose(_alloc)
    , command(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef uint8_t _command_type;
  _command_type command;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MOVE)
  #undef MOVE
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(RESET)
  #undef RESET
#endif
#if defined(_WIN32) && defined(START)
  #undef START
#endif
#if defined(_WIN32) && defined(HOME)
  #undef HOME
#endif

  enum {
    MOVE = 0u,
    STOP = 1u,
    RESET = 2u,
    START = 3u,
    HOME = 4u,
  };


  typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ArchieRailCmdGoal_

typedef ::cares_msgs::ArchieRailCmdGoal_<std::allocator<void> > ArchieRailCmdGoal;

typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdGoal > ArchieRailCmdGoalPtr;
typedef boost::shared_ptr< ::cares_msgs::ArchieRailCmdGoal const> ArchieRailCmdGoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.target_pose == rhs.target_pose &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fa4c0e094781ef3d57da780026312c0";
  }

  static const char* value(const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fa4c0e094781ef3ULL;
  static const uint64_t static_value2 = 0xd57da780026312c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/ArchieRailCmdGoal";
  }

  static const char* value(const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"std_msgs/Header header\n"
"\n"
"geometry_msgs/PoseStamped target_pose\n"
"\n"
"uint8 MOVE  = 0\n"
"uint8 STOP  = 1\n"
"uint8 RESET = 2\n"
"uint8 START = 3\n"
"uint8 HOME  = 4\n"
"\n"
"# 5-255 reserved for future use\n"
"uint8 command\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.target_pose);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArchieRailCmdGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::ArchieRailCmdGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_ARCHIERAILCMDGOAL_H
