// Generated by gencpp from file cares_msgs/ArucoDetect.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_ARUCODETECT_H
#define CARES_MSGS_MESSAGE_ARUCODETECT_H

#include <ros/service_traits.h>


#include <cares_msgs/ArucoDetectRequest.h>
#include <cares_msgs/ArucoDetectResponse.h>


namespace cares_msgs
{

struct ArucoDetect
{

typedef ArucoDetectRequest Request;
typedef ArucoDetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArucoDetect
} // namespace cares_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cares_msgs::ArucoDetect > {
  static const char* value()
  {
    return "46b24f939212136602a01afc5ea1221e";
  }

  static const char* value(const ::cares_msgs::ArucoDetect&) { return value(); }
};

template<>
struct DataType< ::cares_msgs::ArucoDetect > {
  static const char* value()
  {
    return "cares_msgs/ArucoDetect";
  }

  static const char* value(const ::cares_msgs::ArucoDetect&) { return value(); }
};


// service_traits::MD5Sum< ::cares_msgs::ArucoDetectRequest> should match
// service_traits::MD5Sum< ::cares_msgs::ArucoDetect >
template<>
struct MD5Sum< ::cares_msgs::ArucoDetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cares_msgs::ArucoDetect >::value();
  }
  static const char* value(const ::cares_msgs::ArucoDetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cares_msgs::ArucoDetectRequest> should match
// service_traits::DataType< ::cares_msgs::ArucoDetect >
template<>
struct DataType< ::cares_msgs::ArucoDetectRequest>
{
  static const char* value()
  {
    return DataType< ::cares_msgs::ArucoDetect >::value();
  }
  static const char* value(const ::cares_msgs::ArucoDetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cares_msgs::ArucoDetectResponse> should match
// service_traits::MD5Sum< ::cares_msgs::ArucoDetect >
template<>
struct MD5Sum< ::cares_msgs::ArucoDetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cares_msgs::ArucoDetect >::value();
  }
  static const char* value(const ::cares_msgs::ArucoDetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cares_msgs::ArucoDetectResponse> should match
// service_traits::DataType< ::cares_msgs::ArucoDetect >
template<>
struct DataType< ::cares_msgs::ArucoDetectResponse>
{
  static const char* value()
  {
    return DataType< ::cares_msgs::ArucoDetect >::value();
  }
  static const char* value(const ::cares_msgs::ArucoDetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARES_MSGS_MESSAGE_ARUCODETECT_H
