// Generated by gencpp from file cares_msgs/Cane.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_CANE_H
#define CARES_MSGS_MESSAGE_CANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cares_msgs/Node.h>
#include <cares_msgs/Node.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct Cane_
{
  typedef Cane_<ContainerAllocator> Type;

  Cane_()
    : cane_id(0)
    , cane_type(0)
    , internode_length(0.0)
    , internode_width(0.0)
    , node_count(0)
    , node_list()
    , origin_node()  {
    }
  Cane_(const ContainerAllocator& _alloc)
    : cane_id(0)
    , cane_type(0)
    , internode_length(0.0)
    , internode_width(0.0)
    , node_count(0)
    , node_list(_alloc)
    , origin_node(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _cane_id_type;
  _cane_id_type cane_id;

   typedef uint8_t _cane_type_type;
  _cane_type_type cane_type;

   typedef double _internode_length_type;
  _internode_length_type internode_length;

   typedef double _internode_width_type;
  _internode_width_type internode_width;

   typedef uint8_t _node_count_type;
  _node_count_type node_count;

   typedef std::vector< ::cares_msgs::Node_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cares_msgs::Node_<ContainerAllocator> >> _node_list_type;
  _node_list_type node_list;

   typedef  ::cares_msgs::Node_<ContainerAllocator>  _origin_node_type;
  _origin_node_type origin_node;





  typedef boost::shared_ptr< ::cares_msgs::Cane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::Cane_<ContainerAllocator> const> ConstPtr;

}; // struct Cane_

typedef ::cares_msgs::Cane_<std::allocator<void> > Cane;

typedef boost::shared_ptr< ::cares_msgs::Cane > CanePtr;
typedef boost::shared_ptr< ::cares_msgs::Cane const> CaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::Cane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::Cane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::Cane_<ContainerAllocator1> & lhs, const ::cares_msgs::Cane_<ContainerAllocator2> & rhs)
{
  return lhs.cane_id == rhs.cane_id &&
    lhs.cane_type == rhs.cane_type &&
    lhs.internode_length == rhs.internode_length &&
    lhs.internode_width == rhs.internode_width &&
    lhs.node_count == rhs.node_count &&
    lhs.node_list == rhs.node_list &&
    lhs.origin_node == rhs.origin_node;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::Cane_<ContainerAllocator1> & lhs, const ::cares_msgs::Cane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::Cane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::Cane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::Cane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::Cane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::Cane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::Cane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::Cane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "990229165f52a870a5751518d654608f";
  }

  static const char* value(const ::cares_msgs::Cane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x990229165f52a870ULL;
  static const uint64_t static_value2 = 0xa5751518d654608fULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::Cane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/Cane";
  }

  static const char* value(const ::cares_msgs::Cane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::Cane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 cane_id\n"
"uint8 cane_type\n"
"\n"
"float64 internode_length\n"
"float64 internode_width\n"
"uint8 node_count\n"
"\n"
"cares_msgs/Node[] node_list\n"
"cares_msgs/Node origin_node\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/Node\n"
"uint32 node_id\n"
"\n"
"#Node Type\n"
"uint8  PRIMARY_ORIGIN_NODE = 0\n"
"uint8  REGULAR_NODE = 1\n"
"uint8  MULTI_NODE = 2\n"
"uint8  UNLINKED_NODE = 3\n"
"uint8  node_type\n"
"\n"
"geometry_msgs/Point position\n"
"\n"
"uint32 sequencial_neighbour_id\n"
"cares_msgs/NodeNeighbourInfo[] neighbours\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/NodeNeighbourInfo\n"
"uint32 neighbour_id\n"
"float64 internode_length\n"
"float64 internode_width\n"
;
  }

  static const char* value(const ::cares_msgs::Cane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::Cane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cane_id);
      stream.next(m.cane_type);
      stream.next(m.internode_length);
      stream.next(m.internode_width);
      stream.next(m.node_count);
      stream.next(m.node_list);
      stream.next(m.origin_node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::Cane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::Cane_<ContainerAllocator>& v)
  {
    s << indent << "cane_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cane_id);
    s << indent << "cane_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cane_type);
    s << indent << "internode_length: ";
    Printer<double>::stream(s, indent + "  ", v.internode_length);
    s << indent << "internode_width: ";
    Printer<double>::stream(s, indent + "  ", v.internode_width);
    s << indent << "node_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.node_count);
    s << indent << "node_list[]" << std::endl;
    for (size_t i = 0; i < v.node_list.size(); ++i)
    {
      s << indent << "  node_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cares_msgs::Node_<ContainerAllocator> >::stream(s, indent + "    ", v.node_list[i]);
    }
    s << indent << "origin_node: ";
    s << std::endl;
    Printer< ::cares_msgs::Node_<ContainerAllocator> >::stream(s, indent + "  ", v.origin_node);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_CANE_H
