// Generated by gencpp from file cares_msgs/CutGoal.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_CUTGOAL_H
#define CARES_MSGS_MESSAGE_CUTGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cares_msgs/CutPoint.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct CutGoal_
{
  typedef CutGoal_<ContainerAllocator> Type;

  CutGoal_()
    : command(0)
    , cutting_frame()
    , planning_frame()
    , cut_points()  {
    }
  CutGoal_(const ContainerAllocator& _alloc)
    : command(0)
    , cutting_frame(_alloc)
    , planning_frame(_alloc)
    , cut_points(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cutting_frame_type;
  _cutting_frame_type cutting_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _planning_frame_type;
  _planning_frame_type planning_frame;

   typedef std::vector< ::cares_msgs::CutPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cares_msgs::CutPoint_<ContainerAllocator> >> _cut_points_type;
  _cut_points_type cut_points;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CUT)
  #undef CUT
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif

  enum {
    CUT = 0u,
    STOP = 1u,
  };


  typedef boost::shared_ptr< ::cares_msgs::CutGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::CutGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CutGoal_

typedef ::cares_msgs::CutGoal_<std::allocator<void> > CutGoal;

typedef boost::shared_ptr< ::cares_msgs::CutGoal > CutGoalPtr;
typedef boost::shared_ptr< ::cares_msgs::CutGoal const> CutGoalConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::CutGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::CutGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::CutGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::CutGoal_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.cutting_frame == rhs.cutting_frame &&
    lhs.planning_frame == rhs.planning_frame &&
    lhs.cut_points == rhs.cut_points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::CutGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::CutGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::CutGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::CutGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::CutGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::CutGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::CutGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::CutGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::CutGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f760b5a102c579d359a8e31180574d7a";
  }

  static const char* value(const ::cares_msgs::CutGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf760b5a102c579d3ULL;
  static const uint64_t static_value2 = 0x59a8e31180574d7aULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::CutGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/CutGoal";
  }

  static const char* value(const ::cares_msgs::CutGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::CutGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 CUT = 0\n"
"uint8 STOP = 1\n"
"uint8 command\n"
"\n"
"string cutting_frame\n"
"string planning_frame\n"
"cares_msgs/CutPoint[] cut_points\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/CutPoint\n"
"geometry_msgs/Point cut_point_a\n"
"geometry_msgs/Point cut_point_b\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cares_msgs::CutGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::CutGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.cutting_frame);
      stream.next(m.planning_frame);
      stream.next(m.cut_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CutGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::CutGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::CutGoal_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "cutting_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cutting_frame);
    s << indent << "planning_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.planning_frame);
    s << indent << "cut_points[]" << std::endl;
    for (size_t i = 0; i < v.cut_points.size(); ++i)
    {
      s << indent << "  cut_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cares_msgs::CutPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.cut_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_CUTGOAL_H
