// Generated by gencpp from file cares_msgs/DetectionResponse.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_DETECTIONRESPONSE_H
#define CARES_MSGS_MESSAGE_DETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cares_msgs/InstanceMasks.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct DetectionResponse_
{
  typedef DetectionResponse_<ContainerAllocator> Type;

  DetectionResponse_()
    : results()  {
    }
  DetectionResponse_(const ContainerAllocator& _alloc)
    : results(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cares_msgs::InstanceMasks_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cares_msgs::InstanceMasks_<ContainerAllocator> >> _results_type;
  _results_type results;





  typedef boost::shared_ptr< ::cares_msgs::DetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::DetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionResponse_

typedef ::cares_msgs::DetectionResponse_<std::allocator<void> > DetectionResponse;

typedef boost::shared_ptr< ::cares_msgs::DetectionResponse > DetectionResponsePtr;
typedef boost::shared_ptr< ::cares_msgs::DetectionResponse const> DetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::DetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::DetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::DetectionResponse_<ContainerAllocator1> & lhs, const ::cares_msgs::DetectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.results == rhs.results;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::DetectionResponse_<ContainerAllocator1> & lhs, const ::cares_msgs::DetectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::DetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::DetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::DetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d35ecd7cde940f12bbae788dd93dab2b";
  }

  static const char* value(const ::cares_msgs::DetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd35ecd7cde940f12ULL;
  static const uint64_t static_value2 = 0xbbae788dd93dab2bULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/DetectionResponse";
  }

  static const char* value(const ::cares_msgs::DetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/InstanceMasks[] results\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/InstanceMasks\n"
"std_msgs/Header header\n"
"\n"
"# ID for the associated image\n"
"uint32 image_id\n"
"\n"
"# Bounding boxes in pixels\n"
"sensor_msgs/RegionOfInterest[] boxes\n"
"\n"
"# Integer label IDs for each bounding box\n"
"int32[] labels\n"
"\n"
"# Float probability scores of the class_id\n"
"float32[] scores\n"
"\n"
"# Instance masks as Images\n"
"# 0: Mask [0 - 1]\n"
"sensor_msgs/Image[] masks\n"
"\n"
"# Instance masks as Images\n"
"# 0: Mask [0 - 1]\n"
"# 1: Label\n"
"# 2: Instance\n"
"sensor_msgs/Image aggregated_mask\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::cares_msgs::DetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::DetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::DetectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "results[]" << std::endl;
    for (size_t i = 0; i < v.results.size(); ++i)
    {
      s << indent << "  results[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cares_msgs::InstanceMasks_<ContainerAllocator> >::stream(s, indent + "    ", v.results[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_DETECTIONRESPONSE_H
