// Generated by gencpp from file cares_msgs/ExtractCutPoints.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_EXTRACTCUTPOINTS_H
#define CARES_MSGS_MESSAGE_EXTRACTCUTPOINTS_H

#include <ros/service_traits.h>


#include <cares_msgs/ExtractCutPointsRequest.h>
#include <cares_msgs/ExtractCutPointsResponse.h>


namespace cares_msgs
{

struct ExtractCutPoints
{

typedef ExtractCutPointsRequest Request;
typedef ExtractCutPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExtractCutPoints
} // namespace cares_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cares_msgs::ExtractCutPoints > {
  static const char* value()
  {
    return "604cb71cb97a878dca81952efa8bdc5a";
  }

  static const char* value(const ::cares_msgs::ExtractCutPoints&) { return value(); }
};

template<>
struct DataType< ::cares_msgs::ExtractCutPoints > {
  static const char* value()
  {
    return "cares_msgs/ExtractCutPoints";
  }

  static const char* value(const ::cares_msgs::ExtractCutPoints&) { return value(); }
};


// service_traits::MD5Sum< ::cares_msgs::ExtractCutPointsRequest> should match
// service_traits::MD5Sum< ::cares_msgs::ExtractCutPoints >
template<>
struct MD5Sum< ::cares_msgs::ExtractCutPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cares_msgs::ExtractCutPoints >::value();
  }
  static const char* value(const ::cares_msgs::ExtractCutPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cares_msgs::ExtractCutPointsRequest> should match
// service_traits::DataType< ::cares_msgs::ExtractCutPoints >
template<>
struct DataType< ::cares_msgs::ExtractCutPointsRequest>
{
  static const char* value()
  {
    return DataType< ::cares_msgs::ExtractCutPoints >::value();
  }
  static const char* value(const ::cares_msgs::ExtractCutPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cares_msgs::ExtractCutPointsResponse> should match
// service_traits::MD5Sum< ::cares_msgs::ExtractCutPoints >
template<>
struct MD5Sum< ::cares_msgs::ExtractCutPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cares_msgs::ExtractCutPoints >::value();
  }
  static const char* value(const ::cares_msgs::ExtractCutPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cares_msgs::ExtractCutPointsResponse> should match
// service_traits::DataType< ::cares_msgs::ExtractCutPoints >
template<>
struct DataType< ::cares_msgs::ExtractCutPointsResponse>
{
  static const char* value()
  {
    return DataType< ::cares_msgs::ExtractCutPoints >::value();
  }
  static const char* value(const ::cares_msgs::ExtractCutPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARES_MSGS_MESSAGE_EXTRACTCUTPOINTS_H
