// Generated by gencpp from file cares_msgs/MappingFeedback.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_MAPPINGFEEDBACK_H
#define CARES_MSGS_MESSAGE_MAPPINGFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cares_msgs/ScanningFeedback.h>
#include <cares_msgs/MetricExtractionFeedback.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct MappingFeedback_
{
  typedef MappingFeedback_<ContainerAllocator> Type;

  MappingFeedback_()
    : status(0)
    , scanning_feedback()
    , metric_feedback()
    , count(0)
    , total(0)  {
    }
  MappingFeedback_(const ContainerAllocator& _alloc)
    : status(0)
    , scanning_feedback(_alloc)
    , metric_feedback(_alloc)
    , count(0)
    , total(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef std::vector< ::cares_msgs::ScanningFeedback_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >> _scanning_feedback_type;
  _scanning_feedback_type scanning_feedback;

   typedef std::vector< ::cares_msgs::MetricExtractionFeedback_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cares_msgs::MetricExtractionFeedback_<ContainerAllocator> >> _metric_feedback_type;
  _metric_feedback_type metric_feedback;

   typedef uint8_t _count_type;
  _count_type count;

   typedef uint8_t _total_type;
  _total_type total;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INIT)
  #undef INIT
#endif
#if defined(_WIN32) && defined(SCANNING)
  #undef SCANNING
#endif
#if defined(_WIN32) && defined(EXTRACTING)
  #undef EXTRACTING
#endif
#if defined(_WIN32) && defined(ACTUATING)
  #undef ACTUATING
#endif
#if defined(_WIN32) && defined(STOPPING)
  #undef STOPPING
#endif

  enum {
    INIT = 0u,
    SCANNING = 1u,
    EXTRACTING = 2u,
    ACTUATING = 3u,
    STOPPING = 4u,
  };


  typedef boost::shared_ptr< ::cares_msgs::MappingFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::MappingFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MappingFeedback_

typedef ::cares_msgs::MappingFeedback_<std::allocator<void> > MappingFeedback;

typedef boost::shared_ptr< ::cares_msgs::MappingFeedback > MappingFeedbackPtr;
typedef boost::shared_ptr< ::cares_msgs::MappingFeedback const> MappingFeedbackConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::MappingFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::MappingFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::MappingFeedback_<ContainerAllocator1> & lhs, const ::cares_msgs::MappingFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.scanning_feedback == rhs.scanning_feedback &&
    lhs.metric_feedback == rhs.metric_feedback &&
    lhs.count == rhs.count &&
    lhs.total == rhs.total;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::MappingFeedback_<ContainerAllocator1> & lhs, const ::cares_msgs::MappingFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MappingFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MappingFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MappingFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ae1ba1e50a20d1a52a1745cc6000ec6";
  }

  static const char* value(const ::cares_msgs::MappingFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ae1ba1e50a20d1aULL;
  static const uint64_t static_value2 = 0x52a1745cc6000ec6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/MappingFeedback";
  }

  static const char* value(const ::cares_msgs::MappingFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
"#Enumeration\n"
"uint8 INIT       = 0\n"
"uint8 SCANNING   = 1\n"
"uint8 EXTRACTING = 2\n"
"uint8 ACTUATING  = 3\n"
"uint8 STOPPING   = 4\n"
"#Task status\n"
"uint8 status\n"
"\n"
"cares_msgs/ScanningFeedback[] scanning_feedback\n"
"cares_msgs/MetricExtractionFeedback[] metric_feedback\n"
"\n"
"uint8 count\n"
"uint8 total\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ScanningFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
"#Enumeration\n"
"uint8 INIT       = 0\n"
"uint8 MARKER     = 1\n"
"uint8 CAPTURING  = 2\n"
"uint8 ERROR      = 3\n"
"#Task status\n"
"uint8 status\n"
"\n"
"#Enumeration\n"
"uint8 MOVING  = 4\n"
"uint8 IDLE    = 5\n"
"uint8 arm_status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/MetricExtractionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback definition\n"
"#Enumeration\n"
"uint8 CAPTURING = 0\n"
"uint8 MEASURING = 1\n"
"#Task status\n"
"uint8 status\n"
"\n"
"uint8 processed\n"
"uint8 queued\n"
"\n"
;
  }

  static const char* value(const ::cares_msgs::MappingFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.scanning_feedback);
      stream.next(m.metric_feedback);
      stream.next(m.count);
      stream.next(m.total);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MappingFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::MappingFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::MappingFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "scanning_feedback[]" << std::endl;
    for (size_t i = 0; i < v.scanning_feedback.size(); ++i)
    {
      s << indent << "  scanning_feedback[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >::stream(s, indent + "    ", v.scanning_feedback[i]);
    }
    s << indent << "metric_feedback[]" << std::endl;
    for (size_t i = 0; i < v.metric_feedback.size(); ++i)
    {
      s << indent << "  metric_feedback[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cares_msgs::MetricExtractionFeedback_<ContainerAllocator> >::stream(s, indent + "    ", v.metric_feedback[i]);
    }
    s << indent << "count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.count);
    s << indent << "total: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.total);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_MAPPINGFEEDBACK_H
