// Generated by gencpp from file cares_msgs/MergeExtractorResponse.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_MERGEEXTRACTORRESPONSE_H
#define CARES_MSGS_MESSAGE_MERGEEXTRACTORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cares_msgs
{
template <class ContainerAllocator>
struct MergeExtractorResponse_
{
  typedef MergeExtractorResponse_<ContainerAllocator> Type;

  MergeExtractorResponse_()
    : result(false)  {
    }
  MergeExtractorResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MergeExtractorResponse_

typedef ::cares_msgs::MergeExtractorResponse_<std::allocator<void> > MergeExtractorResponse;

typedef boost::shared_ptr< ::cares_msgs::MergeExtractorResponse > MergeExtractorResponsePtr;
typedef boost::shared_ptr< ::cares_msgs::MergeExtractorResponse const> MergeExtractorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator1> & lhs, const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator1> & lhs, const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/MergeExtractorResponse";
  }

  static const char* value(const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MergeExtractorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::MergeExtractorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::MergeExtractorResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_MERGEEXTRACTORRESPONSE_H
